import os
import json
import argparse

def format_factoid(text):
    """
    Factoid: exact_answer expects an array of arrays of strings.
    E.g., [["pneumonia"]]
    Max 5 entities. We just wrap the text in a single list of list for now.
    """
    cleaned = text.strip()
    # Remove trailing period if generated by the model
    if cleaned.endswith('.'):
        cleaned = cleaned[:-1]
    return [[cleaned.strip()]]

def format_list(text):
    """
    List: exact_answer expects an array of arrays of strings.
    E.g., [["pneumonia"], ["influenza"]]
    Max 100 entities. We split by comma.
    """
    cleaned = text.strip()
    if cleaned.endswith('.'):
        cleaned = cleaned[:-1]
        
    # Split by comma and clean up spaces
    entities = [e.strip() for e in cleaned.split(',')]
    entities = [e for e in entities if e] # remove empty strings
    
    # Cap at 100 entities per BioASQ guidelines
    return [[e] for e in entities[:100]]

def format_yesno(text):
    """
    Yesno: exact_answer expects string "yes" or "no".
    """
    cleaned = text.strip().lower()
    
    if 'yes' in cleaned:
        return 'yes'
    elif 'no' in cleaned:
        return 'no'
        
    print(f"Warning: Model generated gibberish for YESNO, defaulting to 'yes'. Text was: {text[:50]}...")
    return 'yes'  # fallback

def map_predictions(orig_data, pred_dir):
    """
    Reads predict.json for each question type and maps them to the original questions by body text.
    """
    # Build a lookup dictionary: { question_type: { question_body: raw_text } }
    predictions_lookup = {'yesno': {}, 'factoid': {}, 'list': {}, 'summary': {}}
    
    for q_type in predictions_lookup.keys():
        pred_file = os.path.join(pred_dir, q_type, 'predict.json')
        if os.path.exists(pred_file):
            with open(pred_file, 'r', encoding='utf-8') as f:
                preds = json.load(f)
                for p in preds:
                    predictions_lookup[q_type][p['question']] = p['text']
        else:
            print(f"Warning: Could not find prediction file {pred_file}")

    merged_questions = []
    
    for q in orig_data.get('questions', []):
        q_type = q.get('type')
        q_body = q.get('body')
        
        # Make a copy of the original question to avoid mutating the original reference
        merged_q = dict(q)
        
        raw_text = predictions_lookup.get(q_type, {}).get(q_body)
        
        if raw_text is None:
            print(f"Warning: No prediction found for {q_type} question: '{q_body}'")
            merged_questions.append(merged_q)
            continue
            
        # Apply type-specific formatting
        if q_type == 'summary':
            merged_q['ideal_answer'] = raw_text.strip()
        elif q_type == 'yesno':
            merged_q['exact_answer'] = format_yesno(raw_text)
            merged_q['ideal_answer'] = ""
        elif q_type == 'factoid':
            merged_q['exact_answer'] = format_factoid(raw_text)
            merged_q['ideal_answer'] = ""
        elif q_type == 'list':
            merged_q['exact_answer'] = format_list(raw_text)
            merged_q['ideal_answer'] = ""
            
        merged_questions.append(merged_q)
        
    return {"questions": merged_questions}

def main():
    parser = argparse.ArgumentParser(description="Merge BioASQ predictions into a single valid JSON.")
    parser.add_argument("--orig_file", type=str, default="data/bioasq-batch1.json",
                        help="Path to the original BioASQ JSON file (e.g. bioasq-batch1.json)")
    parser.add_argument("--pred_dir", type=str, required=True,
                        help="Path to the directory containing yesno, list, factoid, summary output folders (e.g. output/.../combine/)")
    parser.add_argument("--output_file", type=str, default="bioasq_merged_output.json",
                        help="Path to save the final merged JSON file.")
    
    args = parser.parse_args()
    
    print(f"Loading original data from {args.orig_file}...")
    with open(args.orig_file, 'r', encoding='utf-8') as f:
        orig_data = json.load(f)
        
    print(f"Merging predictions from {args.pred_dir}...")
    merged_data = map_predictions(orig_data, args.pred_dir)
    
    print(f"Saving merged results to {args.output_file}...")
    with open(args.output_file, 'w', encoding='utf-8') as f:
        json.dump(merged_data, f, indent=2, ensure_ascii=False)
        
    print("Done!")

if __name__ == "__main__":
    main()
